import { NextFunction, Request, Response } from "express";

// Browser-based MCP clients (claude.ai in particular) call /mcp with fetch(),
// so every request is subject to the same-origin policy. Two consequences are
// easy to miss when the server is only ever tested with curl:
//
//  1. A cross-origin POST carrying an Authorization header is "not simple", so
//     the browser first sends an OPTIONS preflight. Per the Fetch standard a
//     preflight carries NO Authorization header — it is generated by the
//     browser, not by the client code. A server that authenticates OPTIONS
//     therefore answers 401, the browser aborts, and the real POST is never
//     sent. From the server's logs this looks exactly like "the client
//     completed OAuth and then called /mcp without a token".
//
//  2. Response headers are invisible to client JavaScript unless they are
//     named in Access-Control-Expose-Headers. Mcp-Session-Id has to be
//     readable or the client cannot echo it on follow-up requests, and
//     WWW-Authenticate has to be readable or the client cannot find the
//     resource_metadata URL that starts the OAuth flow.
//
// See ISSUES.md for the captured request/response pairs.

// Headers a Streamable HTTP client sends. Anything not listed here is rejected
// by the browser at preflight time, before the request leaves the machine.
const ALLOWED_HEADERS = [
  "Authorization",
  "Content-Type",
  "Accept",
  "Mcp-Session-Id",
  "Mcp-Protocol-Version",
  "Last-Event-ID",
].join(", ");

// Headers the client must be able to read off the response.
const EXPOSED_HEADERS = [
  "Mcp-Session-Id",
  "WWW-Authenticate",
  "Last-Event-ID",
].join(", ");

const ALLOWED_METHODS = "GET, POST, DELETE, OPTIONS";
const PREFLIGHT_MAX_AGE_SECONDS = 86400;

// Optional allowlist. Unset means "any origin", which is safe here because
// every /mcp request still has to carry a bearer token — an attacker's page
// can reach the endpoint but cannot authenticate to it. Set it to lock the
// server to known clients anyway (e.g. "https://claude.ai").
export function parseAllowedOrigins(value: string | undefined): string[] | null {
  if (!value) return null;
  const origins = value
    .split(",")
    .map((origin) => origin.trim())
    .filter(Boolean);
  return origins.length ? origins : null;
}

export function createCorsMiddleware(allowedOrigins: string[] | null) {
  return function cors(req: Request, res: Response, next: NextFunction): void {
    const origin = req.headers.origin;

    if (typeof origin === "string") {
      if (allowedOrigins && !allowedOrigins.includes(origin)) {
        // No CORS headers: the browser blocks the response, and a non-browser
        // client that sent an Origin header by accident is unaffected.
        if (req.method === "OPTIONS") {
          res.status(403).end();
          return;
        }
        next();
        return;
      }

      // The origin is echoed rather than answered with "*" so the same code
      // path keeps working if a client ever sends credentials, and Vary keeps
      // caches from serving one origin's response to another.
      res.setHeader("Access-Control-Allow-Origin", origin);
      res.setHeader("Vary", "Origin");
    } else if (!allowedOrigins) {
      res.setHeader("Access-Control-Allow-Origin", "*");
    }

    res.setHeader("Access-Control-Allow-Methods", ALLOWED_METHODS);
    res.setHeader("Access-Control-Allow-Headers", ALLOWED_HEADERS);
    res.setHeader("Access-Control-Expose-Headers", EXPOSED_HEADERS);

    // The preflight is answered here, before any authentication middleware
    // runs. This is the whole point: it never carries a token.
    if (req.method === "OPTIONS") {
      res.setHeader("Access-Control-Max-Age", String(PREFLIGHT_MAX_AGE_SECONDS));
      res.status(204).end();
      return;
    }

    next();
  };
}
